#!/usr/bin/env node
/**
 * Regenerate a shoot's composition registry from the .tsx files build-reel wrote.
 *
 *   node scripts/sync-root.mjs --slug <shoot>
 *
 * Writes src/compositions/<shoot>/registry.tsx exporting <ShootRegistry/>, so
 * Root.tsx only needs one import per shoot no matter how many variations exist.
 */
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

const args = process.argv.slice(2);
const slug = (() => {
  const i = args.indexOf("--slug");
  return i >= 0 ? args[i + 1] : null;
})();
if (!slug) {
  console.error("Usage: node scripts/sync-root.mjs --slug <shoot>");
  process.exit(1);
}

const dir = join(process.cwd(), "src", "compositions", slug);
const comps = readdirSync(dir)
  .filter((f) => f.endsWith(".tsx") && f !== "registry.tsx")
  .map((f) => f.replace(/\.tsx$/, ""))
  .filter((name) => /export const [A-Z]/.test(readFileSync(join(dir, name + ".tsx"), "utf8")))
  .sort();

const Pascal = slug.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const body = `import React from "react";
import { Composition, Folder } from "remotion";
${comps.map((c) => `import { ${c}, ${c.toUpperCase()}_METADATA } from "./${c}";`).join("\n")}

/** Auto-generated by scripts/sync-root.mjs — do not hand-edit. */
export const ${Pascal}Registry: React.FC = () => (
  <Folder name="${Pascal}">
${comps
  .map(
    (c) => `    <Composition
      id="${c}"
      component={${c}}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={${c.toUpperCase()}_METADATA}
    />`,
  )
  .join("\n")}
  </Folder>
);
`;
writeFileSync(join(dir, "registry.tsx"), body);
console.log(`✓ src/compositions/${slug}/registry.tsx — ${comps.length} compositions`);
console.log(`  add to Root.tsx:  import { ${Pascal}Registry } from "./compositions/${slug}/registry";  then <${Pascal}Registry />`);
