import React from "react";
import { Composition, Folder } from "remotion";
import { DEFAULT_FORMAT } from "./theme/formats";
import { Demo, DEMO_DURATION_IN_FRAMES } from "./compositions/demo/Demo";
import { MotionDemo, MOTION_DEMO_DURATION } from "./compositions/motion-demo/MotionDemo";
import { EvidenceDemo, EVIDENCE_DEMO_DURATION } from "./compositions/evidence-demo/EvidenceDemo";
import { MetaShootRegistry } from "./compositions/meta-shoot/registry";
import { Live, liveMetadata } from "./compositions/_live/Live";
import { SocialAccordsLaunch, SOCIAL_ACCORDS_LAUNCH_DURATION } from "./compositions/social-accords/SocialAccordsLaunch";

/**
 * Composition registry.
 *
 * Demos live in the "Demos" folder. Each shoot registers its own compositions
 * via one <…Registry /> component generated by scripts/sync-root.mjs, so this
 * file needs only one import per shoot. proj-render.mjs temporarily injects a
 * <ProjRegistry /> here while rendering a project.json and restores this file
 * afterwards — keep the `return (\n    <>` shape it looks for.
 */
export const RemotionRoot: React.FC = () => {
  const v = DEFAULT_FORMAT;
  return (
    <>
      <Folder name="Demos">
        <Composition
          id="Demo"
          component={Demo}
          durationInFrames={DEMO_DURATION_IN_FRAMES}
          fps={v.fps}
          width={v.width}
          height={v.height}
        />
        <Composition
          id="MotionDemo"
          component={MotionDemo}
          durationInFrames={MOTION_DEMO_DURATION}
          fps={v.fps}
          width={v.width}
          height={v.height}
        />
        <Composition
          id="EvidenceDemo"
          component={EvidenceDemo}
          durationInFrames={EVIDENCE_DEMO_DURATION}
          fps={30}
          width={1080}
          height={1920}
        />
      </Folder>

      <MetaShootRegistry />

      <Folder name="Social-Accords">
        <Composition
          id="SocialAccordsLaunchCaptioned"
          component={SocialAccordsLaunch}
          durationInFrames={SOCIAL_ACCORDS_LAUNCH_DURATION}
          fps={30}
          width={1080}
          height={1920}
          defaultProps={{ showCaptions: true }}
        />
        <Composition
          id="SocialAccordsLaunchClean"
          component={SocialAccordsLaunch}
          durationInFrames={SOCIAL_ACCORDS_LAUNCH_DURATION}
          fps={30}
          width={1080}
          height={1920}
          defaultProps={{ showCaptions: false }}
        />
      </Folder>

      {/* Permanent slot for the review server's warm-bundle fast re-render.
          scripts/lib/live-render.mjs writes src/compositions/_live/data.json
          then renders this against a serveUrl bundled once at startup. */}
      <Composition
        id="Live"
        component={Live}
        width={1080}
        height={1920}
        fps={30}
        durationInFrames={1}
        defaultProps={{}}
        calculateMetadata={liveMetadata}
      />

      {/* Real projects get registered below, e.g.:
      <Folder name="miami-outage">
        <Composition id="MiamiOutage" component={MiamiOutage}
          durationInFrames={1800} fps={30} width={1080} height={1920}
          calculateMetadata={miamiOutageMetadata} />
      </Folder>
      */}
    </>
  );
};
