#!/usr/bin/env python3
"""build_scenes.py — manifest-driven animate-stills composition builder.

Reads a scene manifest (JSON) and (re)generates the scene layers and GSAP
timeline of an animate-stills HyperFrames composition. The composition's
index.html is owned by this script between marker comments; everything
outside the markers (styles, fonts, extra layers) is yours to edit and
survives rebuilds. If index.html does not exist, a complete scaffold is
created.

Usage:
    python3 build_scenes.py manifest.json          # build/refresh index.html

Manifest schema (recipes/04-animate-stills.md documents it fully):
{
  "size": [1080, 1080],          // composition pixels [w, h]
  "fps": 30,
  "scenes": [
    {
      "n": 1,                    // 1-based, ordered, contiguous
      "image": "assets/stills/s1.png",
      "window": [0.0, 6.0],      // seconds on the master timeline
      "move": "push-in",         // push-in | pull-back | drift-left |
                                 // drift-right | rise | hold
      "atmosphere": "mist"       // mist | rain | light | none (optional)
    }, ...
  ],
  "captions": [                  // optional, phrase-level
    {"text": "...", "at": [0.5, 5.5]}, ...
  ]
}

Camera moves are linear (documentary register) and span the full window.
Scenes stack in z-order and fade IN over 0.45s at their window start, so
no fade-out choreography is needed. A hidden sentinel pins the timeline's
total duration to the last window's end.
"""
import html
import json
import math
import sys
from pathlib import Path

MARK_SCENES_BEGIN = "<!-- SCENES:BEGIN (generated by build_scenes.py — do not edit inside) -->"
MARK_SCENES_END = "<!-- SCENES:END -->"
MARK_TL_BEGIN = "/* TIMELINE:BEGIN (generated by build_scenes.py — do not edit inside) */"
MARK_TL_END = "/* TIMELINE:END */"

MOVES = {
    "push-in":     ({"scale": 1.03}, {"scale": 1.15}),
    "pull-back":   ({"scale": 1.15}, {"scale": 1.03}),
    "drift-left":  ({"scale": 1.08, "xPercent": 2.2},  {"scale": 1.08, "xPercent": -2.2}),
    "drift-right": ({"scale": 1.08, "xPercent": -2.2}, {"scale": 1.08, "xPercent": 2.2}),
    "rise":        ({"scale": 1.08, "yPercent": 2.2},  {"scale": 1.08, "yPercent": -2.2}),
    "hold":        ({"scale": 1.04}, {"scale": 1.065}),
}
ATMOSPHERES = ("mist", "rain", "light", "none")


def js_props(d: dict) -> str:
    return ", ".join(f"{k}: {v}" for k, v in d.items())


def scene_html(s: dict) -> str:
    atmo = s.get("atmosphere", "none")
    atmo_div = f'\n        <div class="atmo atmo-{atmo}"></div>' if atmo != "none" else ""
    src = html.escape(str(s["image"]), quote=True)
    return (
        f'      <div class="scene" id="sc{s["n"]}">\n'
        f'        <div class="cam" id="cam{s["n"]}" data-layout-allow-overflow>\n'
        f'          <img class="still" src="{src}" alt="" />\n'
        f'        </div>{atmo_div}\n'
        f'      </div>'
    )


def _finite(x) -> bool:
    return isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x)


def timeline_js(manifest: dict) -> str:
    out = []
    total = 0.0
    for s in manifest["scenes"]:
        n = s["n"]
        start, end = float(s["window"][0]), float(s["window"][1])
        dur = end - start
        total = max(total, end)
        frm, to = MOVES[s["move"]]
        out.append(f"      /* scene {n}: {s['move']} {start}-{end}s */")
        if start <= 0.001:
            out.append(f'      tl.set("#sc{n}", {{ autoAlpha: 1 }}, 0);')
        else:
            out.append(f'      tl.set("#sc{n}", {{ autoAlpha: 0 }}, 0);')
            out.append(f'      tl.to("#sc{n}", {{ autoAlpha: 1, duration: 0.45, ease: "power1.inOut" }}, {start:.2f});')
        out.append(
            f'      tl.fromTo("#cam{n}", {{ {js_props(frm)} }}, '
            f'{{ {js_props(to)}, duration: {dur:.2f}, ease: "none" }}, {start:.2f});'
        )
        atmo = s.get("atmosphere", "none")
        if atmo == "mist":
            out.append(f'      tl.fromTo("#sc{n} .atmo", {{ xPercent: -6 }}, {{ xPercent: 6, duration: {dur:.2f}, ease: "none" }}, {start:.2f});')
        elif atmo == "rain":
            out.append(f'      tl.fromTo("#sc{n} .atmo", {{ backgroundPosition: "0px 0px" }}, {{ backgroundPosition: "0px 900px", duration: {dur:.2f}, ease: "none" }}, {start:.2f});')
        elif atmo == "light":
            out.append(f'      tl.fromTo("#sc{n} .atmo", {{ xPercent: -25, opacity: 0.0 }}, {{ xPercent: 25, opacity: 0.55, duration: {dur:.2f}, ease: "sine.inOut" }}, {start:.2f});')
    for i, c in enumerate(manifest.get("captions", []), start=1):
        a, b = float(c["at"][0]), float(c["at"][1])
        out.append(f'      tl.set("#cap{i}", {{ autoAlpha: 0 }}, 0);')
        out.append(f'      tl.to("#cap{i}", {{ autoAlpha: 1, duration: 0.3 }}, {a:.2f});')
        out.append(f'      tl.to("#cap{i}", {{ autoAlpha: 0, duration: 0.3 }}, {max(a, b - 0.3):.2f});')
        total = max(total, b)
    out.append(f'      /* duration sentinel */')
    out.append(f'      tl.to("#__end", {{ autoAlpha: 1, duration: 0.01 }}, {max(total - 0.01, 0):.2f});')
    return "\n".join(out)


def captions_html(manifest: dict) -> str:
    rows = []
    for i, c in enumerate(manifest.get("captions", []), start=1):
        text = html.escape(str(c["text"]))
        rows.append(f'      <div class="caption" id="cap{i}">{text}</div>')
    return "\n".join(rows)


SCAFFOLD = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={w}, height={h}" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: {w}px; height: {h}px; overflow: hidden; background: #0c0c0e; }}
      .stage {{ position: relative; width: {w}px; height: {h}px; }}
      .scene {{ position: absolute; inset: 0; }}
      .cam {{ position: absolute; inset: 0; will-change: transform; }}
      .still {{ width: 100%; height: 100%; object-fit: cover; display: block; }}
      .atmo {{ position: absolute; inset: -12%; pointer-events: none; }}
      .atmo-mist {{ background:
        radial-gradient(42% 30% at 28% 68%, rgba(225,232,238,0.34), transparent 70%),
        radial-gradient(50% 34% at 74% 80%, rgba(208,218,226,0.26), transparent 72%);
        filter: blur(14px); }}
      .atmo-rain {{ background-image: repeating-linear-gradient(
        12deg, rgba(210,222,232,0.0) 0 7px, rgba(210,222,232,0.20) 7px 9px);
        opacity: 0.5; }}
      .atmo-light {{ background: radial-gradient(38% 52% at 50% 38%,
        rgba(255,236,200,0.5), transparent 70%); mix-blend-mode: screen; }}
      .vignette {{ position: absolute; inset: 0; pointer-events: none;
        background: radial-gradient(78% 78% at 50% 46%, transparent 58%, rgba(8,8,10,0.55) 100%); }}
      .caption {{ position: absolute; left: 50%; bottom: 7%; transform: translateX(-50%);
        max-width: 86%; padding: 14px 26px; border-radius: 14px;
        background: rgba(10,10,14,0.78); color: #f3efe7;
        font: 600 30px/1.35 -apple-system, "Segoe UI", sans-serif;
        text-align: center; }}
      #__end {{ position: absolute; width: 1px; height: 1px; opacity: 0; }}
    </style>
  </head>
  <body>
    <div class="stage" data-composition-id="main" data-width="{w}" data-height="{h}" data-start="0">
{scenes_block}
      <div class="vignette"></div>
{captions}
      <div id="__end"></div>
    </div>

    <script>
      window.__timelines = window.__timelines || {{}};
      const tl = gsap.timeline({{ paused: true }});

{tl_block}

      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
"""


def validate(manifest: dict) -> None:
    size = manifest.get("size", [1080, 1080])
    assert (isinstance(size, list) and len(size) == 2
            and all(_finite(v) and 16 <= v <= 8192 for v in size)), f"bad size {size!r}"
    fps = manifest.get("fps", 30)
    assert _finite(fps) and 1 <= fps <= 120, f"bad fps {fps!r}"

    scenes = manifest.get("scenes")
    assert isinstance(scenes, list) and scenes, "manifest needs a non-empty scenes list"
    nums = [s.get("n") for s in scenes]
    assert nums == list(range(1, len(scenes) + 1)), f"scene n must be 1..{len(scenes)} ordered, got {nums}"
    prev = 0.0
    for s in scenes:
        assert s["move"] in MOVES, f"scene {s['n']}: unknown move {s['move']!r}"
        assert s.get("atmosphere", "none") in ATMOSPHERES, f"scene {s['n']}: unknown atmosphere"
        w = s["window"]
        assert (isinstance(w, list) and len(w) == 2 and all(_finite(v) and v >= 0 for v in w)
                and w[1] > w[0]), f"scene {s['n']}: bad window {w}"
        assert w[0] - prev <= 0.2 and w[0] - prev >= -0.001, f"scene {s['n']}: window gap/overlap vs previous"
        prev = w[1]
        img = Path(manifest["__dir"]) / s["image"]
        assert img.is_file(), f"scene {s['n']}: still missing: {img}"
        assert img.open('rb').read(8) == b"\x89PNG\r\n\x1a\n", \
            f"scene {s['n']}: {img} is not a PNG"
    for i, c in enumerate(manifest.get("captions", []), start=1):
        at = c.get("at")
        assert (isinstance(at, list) and len(at) == 2 and all(_finite(v) and v >= 0 for v in at)
                and at[1] > at[0]), f"caption {i}: bad at {at!r}"
        assert isinstance(c.get("text"), str) and c["text"].strip(), f"caption {i}: empty text"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    mpath = Path(sys.argv[1]).resolve()
    manifest = json.loads(mpath.read_text())
    manifest["__dir"] = str(mpath.parent)
    validate(manifest)

    w, h = manifest.get("size", [1080, 1080])
    scenes_block = MARK_SCENES_BEGIN + "\n" + "\n".join(scene_html(s) for s in manifest["scenes"]) + "\n      " + MARK_SCENES_END
    tl_block = "      " + MARK_TL_BEGIN + "\n" + timeline_js(manifest) + "\n      " + MARK_TL_END

    target = mpath.parent / "index.html"
    if target.exists():
        text = target.read_text()
        for begin, end, repl in (
            (MARK_SCENES_BEGIN, MARK_SCENES_END, scenes_block),
            (MARK_TL_BEGIN, MARK_TL_END, tl_block.strip()),
        ):
            assert text.count(begin) == 1 and text.count(end) == 1, \
                f"marker must appear exactly once: {begin[:30]}..."
            i, j = text.find(begin), text.find(end)
            assert i < j, f"end marker precedes begin marker: {begin[:30]}..."
            text = text[:i] + repl + text[j + len(end):]
        target.write_text(text)
        print(f"rebuilt markers in {target} ({len(manifest['scenes'])} scenes)")
    else:
        html = SCAFFOLD.format(w=w, h=h, scenes_block=scenes_block,
                               captions=captions_html(manifest), tl_block=tl_block)
        target.write_text(html)
        print(f"created {target} ({len(manifest['scenes'])} scenes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
