# The hook template Tal approved on Hadad & Qureshi V8 (2026-10-08): "This man/woman [what happened] ... This is the story of NAME",
# with an arrow drawn onto the real person in the first shot. (The scorer-driven "You won't believe / You should try it" hooks
# he called "so bad" are gone; they are in git history, commit c2c9e55.)
# h = five spoken beats: (words, picture key, file or clip start, x / mode, title lead|BIG|BIG2, extra flags)
# map = (first paragraph, flag): countries, not towns.  subs = plain replacements.  collage = redo the illustrations as paper collage.
S = {
 "ai-story-rawan-osman": dict(score=0, line="This woman was raised to hate Jews. This is the story of Rawan Osman.", collage=True,
   h=[("This woman was raised to hate Jews.", 'open', '0.1', '"tall78"', "this_woman_was_raised_to|HATE_JEWS", "arrow:850,600,2.0"),
      ("Then a Jewish shopkeeper", 'P', '"g_counter.jpg"', '50', "then_a|JEWISH|SHOPKEEPER"), ("did one small thing.", 'P', '"g_bags.jpg"', '50', "did|ONE_SMALL|THING"),
      ("This is the story of", 'P', '"stras_petite_france.jpg"', '50', "this_is|THE_STORY|OF"), ("Rawan Osman.", 'open', '0.1', '"tall78"', "|RAWAN|OSMAN")],
   map=("n2", "map:LEBANON,35.8,33.9;FRANCE,7.75,48.58@-6,42,28,54"),
   subs=[('"open": (V, 22.40, 24.70)', '"open": (V, 22.40, 25.60)')]),
 "ai-story-indo-pak-express": dict(score=0, line="This Indian and this Pakistani were supposed to be enemies. This is the story of the Indo-Pak Express.",
   h=[("This Indian", 'bop', '0.1', '"tall50"', "this|INDIAN", "arrow:560,640,0.9"), ("and this Pakistani", 'qur', '0.1', '"tall50"', "and_this|PAKISTANI", "arrow:560,640,1.1"),
      ("were supposed to be enemies.", 'P', '"wagah_cer3.jpg"', '50', "were_supposed_to_be|ENEMIES"), ("They became best friends.", 'hug', '0.0', '"band"', "they_became|BEST|FRIENDS"),
      ("This is the story of the Indo-Pak Express.", 'walk', '0.0', '"band"', "this_is_the_story_of|THE_INDO-PAK|EXPRESS")],
   map=("n3", "map:PAKISTAN,71.5,30.2;INDIA,78.5,24.5@58,92,14,40")),
 "ai-story-megan-phelps": dict(score=0, line="This woman held hate signs at five years old. This is the story of Megan Phelps-Roper.", collage=True,
   h=[("This woman held hate signs at five years old.", 'P', '"megan01.jpg"', '45', "this_woman_held|HATE_SIGNS|AT_FIVE", "arrow:520,700,2.4"),
      ("Then a Jewish man", 'P', '"g_jman.jpg"', '50', "then_a|JEWISH|MAN"), ("answered her with dessert.", 'P', '"shuk21400.jpg"', '50', "answered_her_with|DESSERT"),
      ("This is the story of", 'P', '"church03.jpg"', '42', "this_is|THE_STORY|OF"), ("Megan Phelps-Roper.", 'P', '"nmd19.jpg"', '50', "|MEGAN|PHELPS-ROPER")],
   map=("n2", "map:USA,-95.7,39.05;ISRAEL,35.2,31.8@-128,60,12,58")),
 "ai-story-yehuda-pryce": dict(score=0, line="This man got twenty-four years in prison at nineteen. This is the story of Yehudah Pryce.", collage=True,
   h=[("This man got twenty-four years in prison at nineteen.", 'open', '0.1', '"tall18"', "this_man_got|24_YEARS|AT_NINETEEN", "arrow:540,650,2.8"),
      ("He was a gang member.", 'P', '"g_street.jpg"', '50', "he_was_a|GANG|MEMBER"), ("Then, in prison, he met a rabbi.", 'P', '"jewish_torah_open.jpg"', '50', "in_prison_he_met|A_RABBI"),
      ("This is the story of", 'P', '"prison_pelicanbay_aerial.jpg"', '50', "this_is|THE_STORY|OF"), ("Doctor Yehudah Pryce.", 'end', '0.1', '"tall18"', "Dr.|YEHUDAH|PRYCE")],
   subs=[('"open": (V, 70.6, 73.2)', '"open": (V, 70.6, 74.6)'), ('"card:#111111|he_served|16_YEARS"', '"count:#111111|he_served|16|YEARS"')]),
 "ai-story-korea": dict(score=0, line="These two women come from North and South Korea. This is the story of Hyun Jung-hwa and Ri Bun-hui.",
   h=[("These two women come from North and South Korea.", 'bed', '0.0', '"band"', "these_two_women_come_from|NORTH_AND|SOUTH_KOREA", "arrow:540,700,2.6"),
      ("Their countries are still at war.", 'P', '"jsa_looking_north.jpg"', '50', "their_countries_are|STILL|AT_WAR"), ("They became friends anyway.", 'duo', '0.0', '"band"', "they_became|FRIENDS|ANYWAY"),
      ("This is the story of", 'P', '"flag_unification.jpg"', '50', "this_is|THE_STORY|OF"), ("Hyun Jung-hwa and Ri Bun-hui.", 'bed', '0.6', '"band"', "|HYUN_JUNG-HWA|&amp;_RI_BUN-HUI")],
   map=("n2", "map:NORTH_KOREA,126.2,39.6;SOUTH_KOREA,127.6,36.4@118,136,32,44"),
   subs=[('"bed": (J, 108.4, 111.6, 1.0, "crop=iw:ih*0.72:0:0")', '"bed": (J, 108.4, 111.6, 1.4, "crop=iw:ih*0.72:0:0")')]),
 "ai-story-punjabi-lehar": dict(score=0, line="These two friends are a Muslim and a Sikh. This is the story of Nasir Dhillon and Bhupinder Singh Lovely.",
   h=[("These two friends are a Muslim and a Sikh.", 'duo', '0.0', '"band"', "these_two_friends_are_a|MUSLIM_AND|A_SIKH", "arrow:820,700,2.4"),
      ("With one phone, they reunite families", 'call', '0.2', '"band"', "they_reunite|FAMILIES"), ("that India and Pakistan split in 1947.", 'P', '"p1947_columns.jpg"', '50', "split_in|1947"),
      ("This is the story of", 'P', '"kartarpur_a.jpg"', '50', "this_is|THE_STORY|OF"), ("Nasir Dhillon and Bhupinder Singh Lovely.", 'selfie', '0.0', '"band"', "|NASIR_DHILLON|&amp;_LOVELY_SINGH")],
   map=("n2", "map:PAKISTAN,71.5,30.2;INDIA,78.5,24.5@58,92,14,40"),
   subs=[('"card:#7a1010|they_met_again_after|74_YEARS"', '"count:#7a1010|they_met_again_after|74|YEARS"')]),
 "ai-story-roots": dict(score=0, line="This man lost his brother in the conflict. This is the story of Ali Abu Awwad and Rabbi Hanan Schlesinger.", collage=True,
   h=[("This man lost his brother in the conflict.", 'P', '"ali_portrait.jpg"', '50', "this_man|LOST_HIS|BROTHER", "arrow:540,640,2.3"),
      ("His partner today", 'P', '"gush_lookout.jpg"', '50', "his|PARTNER|TODAY"), ("is an Israeli settler rabbi.", 'P', '"hanan_portrait.jpg"', '82', "an_Israeli|SETTLER|RABBI"),
      ("This is the story of", 'two', '0.0', '"band"', "this_is|THE_STORY|OF"), ("Ali Abu Awwad and Hanan Schlesinger.", 'two', '1.2', '"band"', "|ALI_ABU_AWWAD|&amp;_HANAN_SCHLESINGER")]),
 "ai-story-flight": dict(score=0, line="This pilot was attacked in his own cockpit. This is the story of Captain Smit Machchhar.", collage=True,
   h=[("This pilot was attacked in his own cockpit.", 'smit', '0.1', '"tall50"', "this_pilot_was|ATTACKED_IN|HIS_COCKPIT", "arrow:540,700,2.3"),
      ("About a hundred and eighty people were on board.", 'P', '"cabin_flydubai_max.jpg"', '50', "on_board_about|180|PEOPLE"), ("Then strangers ran to help.", 'P', '"g_aisle.jpg"', '50', "then|STRANGERS|RAN_TO_HELP"),
      ("This is the story of", 'P', '"plane_a6fkf_dxb.jpg"', '50', "this_is|THE_STORY|OF"), ("Captain Smit Machchhar.", 'smit2', '0.1', '"tall50"', "Captain|SMIT|MACHCHHAR")],
   map=("n2", "map:DUBAI,55.3,25.25;TEL_AVIV,34.8,32.1@22,64,10,42"),
   subs=[('"smit": (M, 149.0, 152.0, 1.0, LEFT)', '"smit": (M, 149.0, 153.2, 1.0, LEFT)')]),
 "ai-story-nissim-black": dict(score=0, line="This man lost eight friends on the streets of Seattle. This is the story of Nissim Black.", collage=True,
   h=[("This man lost eight friends on the streets of Seattle.", 'P', '"him_2013_portrait.jpg"', '50', "this_man_lost|EIGHT|FRIENDS", "arrow:330,640,2.8"),
      ("He was selling drugs at twelve.", 'P', '"sea_rainier_1977.jpg"', '50', "selling_drugs_at|TWELVE"), ("Today, he lives in Israel.", 'P', '"jer_kotel_night_portrait.jpg"', '50', "today_he_lives_in|ISRAEL"),
      ("This is the story of", 'P', '"sea_skyline_dusk.jpg"', '50', "this_is|THE_STORY|OF"), ("Nissim Black.", 'P', '"him_2026_stage.jpg"', '50', "|NISSIM|BLACK")],
   map=("n3", "map:SEATTLE,-122.3,47.6;ISRAEL,35.0,31.5@-132,48,14,62")),
 "ai-story-fabian-debora": dict(score=0, line="This man joined a gang at twelve. This is the story of Fabian Debora.", collage=True,
   h=[("This man joined a gang at twelve.", 'prof', '0.1', '"tall50"', "this_man_joined|A_GANG|AT_TWELVE", "arrow:470,650,2.0"),
      ("Today, he teaches kids like him", 'teach', '0.0', '"tall50"', "today_he_teaches|KIDS|LIKE_HIM"), ("to paint.", 'mural', '0.0', '"band"', "to|PAINT"),
      ("This is the story of", 'P', '"bh_street_2012.jpg"', '50', "this_is|THE_STORY|OF"), ("Fabian Debora.", 'sketch', '0.0', '"band"', "|FABIAN|DEBORA")]),
 "ai-story-dor-shachar": dict(score=0, line="This man was once a boy from Gaza, alone in Israel. This is the story of Dor Shachar.", collage=True,
   h=[("This man was once a boy from Gaza, alone in Israel.", 'open', '0.1', '"tall50"', "this_man_was_once|A_BOY|FROM_GAZA", "arrow:540,680,2.8"),
      ("Then a stranger", 'P', '"g_man.jpg"', '50', "then|A_STRANGER"), ("asked him one question.", 'P', '"g_tea.jpg"', '50', "asked_him|ONE|QUESTION"),
      ("This is the story of", 'P', '"rishon_constr_a.jpg"', '50', "this_is|THE_STORY|OF"), ("Dor Shachar.", 'open', '1.2', '"tall50"', "|DOR|SHACHAR")],
   subs=[('CLIPS = {"open": (V, 708.0, 710.6)}', 'CLIPS = {"open": (V, 708.0, 712.2)}')]),
 "ai-story-coptic-oct7": dict(score=0, line="This guy hated Israel, until he asked himself one question. This is the story of Abanoub Samaan.", collage=True,
   h=[("This guy hated Israel,", 'open', '0.1', '"tall50"', "this_guy|HATED|ISRAEL", "arrow:540,700,1.5"),
      ("until he asked himself", 'P', '"g_phone.jpg"', '50', "until_he_asked|HIMSELF"), ("one question.", 'P', '"g_mirror.jpg"', '50', "|ONE|QUESTION"),
      ("This is the story of", 'P', '"coptic_cross_philae.jpg"', '50', "this_is|THE_STORY|OF"), ("Abanoub Samaan.", 'open', '1.4', '"tall50"', "|ABANOUB|SAMAAN")]),
}
