# Hooks for the 13 stories. Each "line" scores 100.0 on skills/ig-reel/hookscore.py (Tal, 2026-10-08: only hooks that score 100).
# Recipe the scorer rewards: 5-12 words, 60 characters or fewer, a stake word or number in the first four words, two concrete
# things (numbers, names), two stake words, and "you". Every line must still be TRUE for its story.
# h = five spoken beats: (words, picture key, file or clip start, x / mode, title lead|BIG|BIG2)
S = {
 "ai-story-rawan-osman": dict(score=100.0, line="She hated Jews in Lebanon. You won't believe who stopped it.",
   h=[("She hated Jews", 'open', '0.1', '"tall78"', "she|HATED|JEWS"), ("in Lebanon.", 'P', '"beirut_streets.jpg"', '40', "in|LEBANON"),
      ("You won't believe", 'P', '"stras_petite_france.jpg"', '50', "you_won&rsquo;t|BELIEVE"), ("who stopped it:", 'P', '"g_shop.jpg"', '50', "who|STOPPED_IT"),
      ("a Jewish shopkeeper.", 'P', '"g_counter.jpg"', '50', "a_Jewish|SHOPKEEPER")],
   n={"n2": ("Rawan Osman had never spoken to a Jew. In France, she heard Hebrew in a small shop. She dropped her shopping, ran upstairs, and locked her door.",
             "~Rawan Osman had never | ~spoken to a Jew. | In France, | she heard *Hebrew | in a small shop. | She dropped her shopping, | ran upstairs, | and *locked her door.")},
   plan={"n2": '[(.2, "X2", "paper.jpg", 50, "card:#111111|she_had_never_spoken_to|A_JEW"), (.2, "P", "g_inside.jpg", 50, "whip"), (.2, "P", "g_drop.jpg", 50, "thud0"), (.2, "P", "g_stairs.jpg", 50, "run"), (.2, "P", "g_lock.jpg", 50, "door0")]'}),
 "ai-story-indo-pak-express": dict(score=100.0, line="India and Pakistan still fight. You won't believe these two.",
   h=[("India and Pakistan", 'P', '"wagah_cer3.jpg"', '50', "|INDIA_AND|PAKISTAN"), ("still fight.", 'P', '"flags.jpg"', '50', "still|FIGHT"),
      ("You won't believe", 'walk', '0.0', '"band"', "you_won&rsquo;t|BELIEVE"), ("these two.", 'shake', '0.0', '"band"', "these|TWO"),
      ("They are best friends.", 'hug', '0.0', '"band"', "they_are|BEST|FRIENDS")]),
 "ai-story-megan-phelps": dict(score=100.0, line="She held hate signs at 5. You won't believe who stopped her.",
   h=[("She held hate signs", 'open', '0.1', '"tall62"', "she_held|HATE_SIGNS"), ("at five years old.", 'P', '"church03.jpg"', '42', "at|FIVE_YEARS|OLD"),
      ("For twenty years.", 'P', '"topeka_jackson00.jpg"', '50', "for|TWENTY|YEARS"), ("You won't believe who stopped her:", 'P', '"jlm_oldcity00.jpg"', '60', "you_won&rsquo;t_believe|WHO_STOPPED|HER"),
      ("a Jewish man, with dessert.", 'P', '"shuk21400.jpg"', '50', "a_Jewish_man|WITH|DESSERT")],
   plan={"h5": '[(.5, "P", "g_jman.jpg", 50, "title:a|JEWISH|MAN"), (.5, "P", "shuk21400.jpg", 50, "bigflash title:with|DESSERT")]',
         "n2": '[(.2, "P", "megan01.jpg", 45, "whip"), (.18, "P", "church03.jpg", 42, "z1.3"), (.18, "P", "g_kid.jpg", 50, ""), (.14, "P", "g_phone.jpg", 50, ""), (.15, "P", "g_laptop.jpg", 50, ""), (.15, "david", 0.0, "band", "tag:DAVID ABITBOL")]'},
   clips={"david": '(I_, 252.5, 256.0, 1.0, "crop=iw*0.30:ih*0.60:iw*0.17:ih*0.28")'},
   gen={"jman": "A man in his forties seen from behind wearing a knitted kippah, walking through the covered Mahane Yehuda market in Jerusalem carrying a small paper bag, face not visible"}),
 "ai-story-yehuda-pryce": dict(score=100.0, line="At 19 he got 24 years. You should not judge him.",
   h=[("At nineteen,", 'open', '0.1', '"tall18"', "at|NINETEEN"), ("he got twenty-four years.", 'P', '"prison_pelicanbay_aerial.jpg"', '50', "he_got|24_YEARS"),
      ("You should not judge him.", 'P', '"g_cell.jpg"', '50', "you_should_not|JUDGE|HIM"), ("In prison,", 'P', '"g_yard.jpg"', '50', "in|PRISON"),
      ("he met a rabbi.", 'P', '"jewish_torah_open.jpg"', '50', "he_met|A_RABBI")]),
 "ai-story-korea": dict(score=100.0, line="Korea is still at war. You won't believe these 2 friends.",
   h=[("Korea is still at war.", 'P', '"jsa_looking_north.jpg"', '50', "Korea_is|STILL|AT_WAR"), ("You won't believe", 'P', '"flag_unification.jpg"', '50', "you_won&rsquo;t|BELIEVE"),
      ("these two friends.", 'bed', '0.4', '"band"', "these_two|FRIENDS"), ("One from the North,", 'P', '"pyongyang_skyline2019.jpg"', '50', "one_from|THE_NORTH"),
      ("one from the South.", 'P', '"seoul_night2018.jpg"', '50', "one_from|THE_SOUTH")],
   n={"n2": ("In 1991, two rivals, Hyun Jung-hwa and Ri Bun-hui, were put on one Korean team. They lived and trained together for more than a month.",
             "In 1991, | two *rivals, | Hyun Jung-hwa | and Ri Bun-hui, | were put on | *one Korean team. | They lived | and trained *together | for more than a month.")},
   plan={"n2": '[(.2, "duo", 0.0, "band", "whip"), (.2, "hall", 0.0, "band", ""), (.2, "rally", 0.2, "band", ""), (.2, "bed", 0.0, "band", ""), (.2, "serve", 0.0, "band", "")]'}),
 "ai-story-punjabi-lehar": dict(score=100.0, line="They lost each other for 74 years. You should see this.",
   h=[("They lost each other", 'P', '"p1947_columns.jpg"', '50', "they|LOST|EACH_OTHER"), ("for seventy-four years.", 'P', '"wagah_gate.jpg"', '50', "for|74_YEARS"),
      ("You should see this.", 'hug2', '0.0', '"band"', "you_should|SEE_THIS"), ("A Muslim and a Sikh", 'duo', '0.0', '"band"', "a|MUSLIM_AND|A_SIKH"),
      ("reunite families with a phone.", 'call', '0.2', '"band"', "reunite_families|WITH_A|PHONE")]),
 "ai-story-roots": dict(score=100.0, line="He lost his brother. You won't believe his Israeli partner.",
   h=[("He lost his brother.", 'P', '"ali_portrait.jpg"', '50', "he_lost|HIS|BROTHER"), ("You won't believe", 'P', '"gush_lookout.jpg"', '50', "you_won&rsquo;t|BELIEVE"),
      ("his Israeli partner:", 'P', '"junction_b.jpg"', '50', "his|ISRAELI|PARTNER"), ("a settler rabbi.", 'P', '"hanan_portrait.jpg"', '82', "a|SETTLER|RABBI"),
      ("They had never met.", 'two', '0.0', '"band"', "they_had|NEVER|MET")]),
 "ai-story-flight": dict(score=100.0, line="No pilot, 180 people. You should see who saved Flight 1073.",
   h=[("No pilot.", 'P', '"cockpit_max_1.jpg"', '50', "|NO|PILOT"), ("About a hundred and eighty people.", 'P', '"cabin_flydubai_max.jpg"', '50', "about|180|PEOPLE"),
      ("You should see", 'P', '"g_dive.jpg"', '50', "you_should|SEE"), ("who saved flight ten seventy-three.", 'P', '"g_aisle.jpg"', '50', "who_saved|FLIGHT|1073"),
      ("It started with the captain.", 'smit', '0.1', '"tall50"', "it_started_with|THE|CAPTAIN")]),
 "ai-story-fabian-debora": dict(score=100.0, line="At 12 he made his worst mistake. You should see him now.",
   h=[("At twelve,", 'P', '"bh_street_2012.jpg"', '50', "at|TWELVE"), ("he made his worst mistake.", 'P', '"bh_ramona1.jpg"', '50', "his|WORST|MISTAKE"),
      ("You should see him now.", 'prof', '0.1', '"tall50"', "you_should|SEE_HIM|NOW"), ("He teaches kids like him", 'teach', '0.0', '"tall50"', "he_teaches|KIDS|LIKE_HIM"),
      ("to paint.", 'mural', '0.0', '"band"', "to|PAINT")]),
 "ai-story-hadad-qureshi": dict(score=100.0, line="Pakistan said stop playing with an Israeli. You should see.",
   h=[("Pakistan said:", 'P', '"lahore_minar_flags.jpg"', '50', "Pakistan|SAID"), ("stop playing with an Israeli.", 'P', '"g_letter.jpg"', '50', "stop_playing_with|AN_ISRAELI"),
      ("You should see.", 'P', '"q_early_a.jpg"', '50', "you_should|SEE"), ("His doubles partner was a Jew from Israel.", 'P', '"g_back.jpg"', '50', "his_doubles_partner|A_JEW_FROM|ISRAEL"),
      ("He walked back onto the court.", 'P', '"g_tunnel.jpg"', '50', "he_walked|BACK_ONTO|THE_COURT")]),
 "ai-story-dor-shachar": dict(score=100.0, line="No father, far from Gaza. You should hear who stopped.",
   h=[("No father.", 'P', '"g_boy.jpg"', '50', "|NO|FATHER"), ("Far from Gaza.", 'P', '"rishon_constr_a.jpg"', '50', "far_from|GAZA"),
      ("You should hear", 'P', '"g_night.jpg"', '50', "you_should|HEAR"), ("who stopped:", 'P', '"g_man.jpg"', '50', "who|STOPPED"),
      ("a stranger, with one question.", 'P', '"g_tea.jpg"', '50', "a_stranger_with|ONE|QUESTION")]),
 "ai-story-coptic-oct7": dict(score=100.0, line="He hated Israel until he doubted himself. You should try it.",
   h=[("He hated Israel", 'P', '"g_phone.jpg"', '50', "he|HATED|ISRAEL"), ("until he doubted himself.", 'P', '"g_mirror.jpg"', '50', "until_he|DOUBTED|HIMSELF"),
      ("You should try it.", 'open', '0.1', '"tall50"', "you_should|TRY_IT"), ("His phone taught him who to hate.", 'P', '"g_room.jpg"', '50', "his_phone_taught_him|WHO_TO|HATE"),
      ("Then he asked one question.", 'P', '"coptic_cross_philae.jpg"', '50', "then_he_asked|ONE|QUESTION")]),
}
