import React from "react";
import { Composition, Folder } from "remotion";
import { C01SHABBATSHALOMV4FAST20SEC, C01SHABBATSHALOMV4FAST20SEC_METADATA } from "./C01SHABBATSHALOMV4FAST20SEC";
import { C02SHALOMSALAAMV5FAST, C02SHALOMSALAAMV5FAST_METADATA } from "./C02SHALOMSALAAMV5FAST";
import { C02SHALOMSALAAMV6HUMAN, C02SHALOMSALAAMV6HUMAN_METADATA } from "./C02SHALOMSALAAMV6HUMAN";
import { C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL, C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL_METADATA } from "./C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL";
import { COMPGIVINGFLOWERSA, COMPGIVINGFLOWERSA_METADATA } from "./COMPGIVINGFLOWERSA";
import { COMPRELIGIONREVEALA, COMPRELIGIONREVEALA_METADATA } from "./COMPRELIGIONREVEALA";
import { COMPRESTAURANTKINDA, COMPRESTAURANTKINDA_METADATA } from "./COMPRESTAURANTKINDA";
import { COMPRESTAURANTKINDB, COMPRESTAURANTKINDB_METADATA } from "./COMPRESTAURANTKINDB";
import { COMPSALAMALAIKUMA, COMPSALAMALAIKUMA_METADATA } from "./COMPSALAMALAIKUMA";
import { COMPSALAMALAIKUMB, COMPSALAMALAIKUMB_METADATA } from "./COMPSALAMALAIKUMB";
import { COMPSHABBATSHALOMA, COMPSHABBATSHALOMA_METADATA } from "./COMPSHABBATSHALOMA";
import { COMPSHABBATSHALOMB, COMPSHABBATSHALOMB_METADATA } from "./COMPSHABBATSHALOMB";
import { COMPSHALOMANDSALAMA, COMPSHALOMANDSALAMA_METADATA } from "./COMPSHALOMANDSALAMA";
import { COMPSHALOMANDSALAMB, COMPSHALOMANDSALAMB_METADATA } from "./COMPSHALOMANDSALAMB";
import { COMPWARMGOODBYESA, COMPWARMGOODBYESA_METADATA } from "./COMPWARMGOODBYESA";
import { COMPWARMGOODBYESB, COMPWARMGOODBYESB_METADATA } from "./COMPWARMGOODBYESB";
import { COMPWHEREFROMA, COMPWHEREFROMA_METADATA } from "./COMPWHEREFROMA";
import { COMPWHEREFROMB, COMPWHEREFROMB_METADATA } from "./COMPWHEREFROMB";
import { FIAHMADIMUSLIM, FIAHMADIMUSLIM_METADATA } from "./FIAHMADIMUSLIM";
import { FIAMERICANMUSLIM, FIAMERICANMUSLIM_METADATA } from "./FIAMERICANMUSLIM";
import { FIANASMUSLIM, FIANASMUSLIM_METADATA } from "./FIANASMUSLIM";
import { FIANGOLAGAYSAFE, FIANGOLAGAYSAFE_METADATA } from "./FIANGOLAGAYSAFE";
import { FIARABCHRISTIANRACISM, FIARABCHRISTIANRACISM_METADATA } from "./FIARABCHRISTIANRACISM";
import { FIBAKERYMAHMOUD, FIBAKERYMAHMOUD_METADATA } from "./FIBAKERYMAHMOUD";
import { FIBAKERYMANAGER25YRS, FIBAKERYMANAGER25YRS_METADATA } from "./FIBAKERYMANAGER25YRS";
import { FIBEACHGUY, FIBEACHGUY_METADATA } from "./FIBEACHGUY";
import { FIBELARUSTOURIST, FIBELARUSTOURIST_METADATA } from "./FIBELARUSTOURIST";
import { FIBERLINSUPPORT, FIBERLINSUPPORT_METADATA } from "./FIBERLINSUPPORT";
import { FICANADACHRISTIAN, FICANADACHRISTIAN_METADATA } from "./FICANADACHRISTIAN";
import { FICHINAAMERICAVISIT, FICHINAAMERICAVISIT_METADATA } from "./FICHINAAMERICAVISIT";
import { FICHRISTIANRESTAURANT, FICHRISTIANRESTAURANT_METADATA } from "./FICHRISTIANRESTAURANT";
import { FICROSSCHRISTIAN, FICROSSCHRISTIAN_METADATA } from "./FICROSSCHRISTIAN";
import { FICROSSSAFEGAY, FICROSSSAFEGAY_METADATA } from "./FICROSSSAFEGAY";
import { FIFLOWERCRYING, FIFLOWERCRYING_METADATA } from "./FIFLOWERCRYING";
import { FIFLOWERLANDED, FIFLOWERLANDED_METADATA } from "./FIFLOWERLANDED";
import { FIFLOWERMUSLIM, FIFLOWERMUSLIM_METADATA } from "./FIFLOWERMUSLIM";
import { FIFLOWERSISTERS, FIFLOWERSISTERS_METADATA } from "./FIFLOWERSISTERS";
import { FIFLOWERUGANDA, FIFLOWERUGANDA_METADATA } from "./FIFLOWERUGANDA";
import { FIHUMUSRESPECT, FIHUMUSRESPECT_METADATA } from "./FIHUMUSRESPECT";
import { FIINDONESIACHRISTIANSAFE, FIINDONESIACHRISTIANSAFE_METADATA } from "./FIINDONESIACHRISTIANSAFE";
import { FIINDONESIAHOME, FIINDONESIAHOME_METADATA } from "./FIINDONESIAHOME";
import { FIINDONESIANINSTAGRAM, FIINDONESIANINSTAGRAM_METADATA } from "./FIINDONESIANINSTAGRAM";
import { FIINDONESIAZIONIST, FIINDONESIAZIONIST_METADATA } from "./FIINDONESIAZIONIST";
import { FIIQAMPEACE, FIIQAMPEACE_METADATA } from "./FIIQAMPEACE";
import { FIIRAQJEWSPERSECUTED, FIIRAQJEWSPERSECUTED_METADATA } from "./FIIRAQJEWSPERSECUTED";
import { FIIRELANDSURPRISED, FIIRELANDSURPRISED_METADATA } from "./FIIRELANDSURPRISED";
import { FIJAFFAMUSLIM, FIJAFFAMUSLIM_METADATA } from "./FIJAFFAMUSLIM";
import { FIJEWHATEEUROPE, FIJEWHATEEUROPE_METADATA } from "./FIJEWHATEEUROPE";
import { FIMEETBADIK, FIMEETBADIK_METADATA } from "./FIMEETBADIK";
import { FIMOROCCOCOUPLE, FIMOROCCOCOUPLE_METADATA } from "./FIMOROCCOCOUPLE";
import { FINIGERIAWORK, FINIGERIAWORK_METADATA } from "./FINIGERIAWORK";
import { FIONEWAYTICKET, FIONEWAYTICKET_METADATA } from "./FIONEWAYTICKET";
import { FIPOLISHPRIEST, FIPOLISHPRIEST_METADATA } from "./FIPOLISHPRIEST";
import { FIRELIGIOUSJEWEXPLAIN, FIRELIGIOUSJEWEXPLAIN_METADATA } from "./FIRELIGIOUSJEWEXPLAIN";
import { FIRELIGIOUSJEWGARMENT, FIRELIGIOUSJEWGARMENT_METADATA } from "./FIRELIGIOUSJEWGARMENT";
import { FISRILANKANWORKER, FISRILANKANWORKER_METADATA } from "./FISRILANKANWORKER";

/** Auto-generated by scripts/sync-root.mjs — do not hand-edit. */
export const MetaShootRegistry: React.FC = () => (
  <Folder name="MetaShoot">
    <Composition
      id="C01SHABBATSHALOMV4FAST20SEC"
      component={C01SHABBATSHALOMV4FAST20SEC}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={C01SHABBATSHALOMV4FAST20SEC_METADATA}
    />
    <Composition
      id="C02SHALOMSALAAMV5FAST"
      component={C02SHALOMSALAAMV5FAST}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={C02SHALOMSALAAMV5FAST_METADATA}
    />
    <Composition
      id="C02SHALOMSALAAMV6HUMAN"
      component={C02SHALOMSALAAMV6HUMAN}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={C02SHALOMSALAAMV6HUMAN_METADATA}
    />
    <Composition
      id="C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL"
      component={C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={C06RESTAURANTCONVERSATIONSV6SHORTEMOTIONAL_METADATA}
    />
    <Composition
      id="COMPGIVINGFLOWERSA"
      component={COMPGIVINGFLOWERSA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPGIVINGFLOWERSA_METADATA}
    />
    <Composition
      id="COMPRELIGIONREVEALA"
      component={COMPRELIGIONREVEALA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPRELIGIONREVEALA_METADATA}
    />
    <Composition
      id="COMPRESTAURANTKINDA"
      component={COMPRESTAURANTKINDA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPRESTAURANTKINDA_METADATA}
    />
    <Composition
      id="COMPRESTAURANTKINDB"
      component={COMPRESTAURANTKINDB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPRESTAURANTKINDB_METADATA}
    />
    <Composition
      id="COMPSALAMALAIKUMA"
      component={COMPSALAMALAIKUMA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSALAMALAIKUMA_METADATA}
    />
    <Composition
      id="COMPSALAMALAIKUMB"
      component={COMPSALAMALAIKUMB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSALAMALAIKUMB_METADATA}
    />
    <Composition
      id="COMPSHABBATSHALOMA"
      component={COMPSHABBATSHALOMA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSHABBATSHALOMA_METADATA}
    />
    <Composition
      id="COMPSHABBATSHALOMB"
      component={COMPSHABBATSHALOMB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSHABBATSHALOMB_METADATA}
    />
    <Composition
      id="COMPSHALOMANDSALAMA"
      component={COMPSHALOMANDSALAMA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSHALOMANDSALAMA_METADATA}
    />
    <Composition
      id="COMPSHALOMANDSALAMB"
      component={COMPSHALOMANDSALAMB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPSHALOMANDSALAMB_METADATA}
    />
    <Composition
      id="COMPWARMGOODBYESA"
      component={COMPWARMGOODBYESA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPWARMGOODBYESA_METADATA}
    />
    <Composition
      id="COMPWARMGOODBYESB"
      component={COMPWARMGOODBYESB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPWARMGOODBYESB_METADATA}
    />
    <Composition
      id="COMPWHEREFROMA"
      component={COMPWHEREFROMA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPWHEREFROMA_METADATA}
    />
    <Composition
      id="COMPWHEREFROMB"
      component={COMPWHEREFROMB}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={COMPWHEREFROMB_METADATA}
    />
    <Composition
      id="FIAHMADIMUSLIM"
      component={FIAHMADIMUSLIM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIAHMADIMUSLIM_METADATA}
    />
    <Composition
      id="FIAMERICANMUSLIM"
      component={FIAMERICANMUSLIM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIAMERICANMUSLIM_METADATA}
    />
    <Composition
      id="FIANASMUSLIM"
      component={FIANASMUSLIM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIANASMUSLIM_METADATA}
    />
    <Composition
      id="FIANGOLAGAYSAFE"
      component={FIANGOLAGAYSAFE}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIANGOLAGAYSAFE_METADATA}
    />
    <Composition
      id="FIARABCHRISTIANRACISM"
      component={FIARABCHRISTIANRACISM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIARABCHRISTIANRACISM_METADATA}
    />
    <Composition
      id="FIBAKERYMAHMOUD"
      component={FIBAKERYMAHMOUD}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIBAKERYMAHMOUD_METADATA}
    />
    <Composition
      id="FIBAKERYMANAGER25YRS"
      component={FIBAKERYMANAGER25YRS}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIBAKERYMANAGER25YRS_METADATA}
    />
    <Composition
      id="FIBEACHGUY"
      component={FIBEACHGUY}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIBEACHGUY_METADATA}
    />
    <Composition
      id="FIBELARUSTOURIST"
      component={FIBELARUSTOURIST}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIBELARUSTOURIST_METADATA}
    />
    <Composition
      id="FIBERLINSUPPORT"
      component={FIBERLINSUPPORT}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIBERLINSUPPORT_METADATA}
    />
    <Composition
      id="FICANADACHRISTIAN"
      component={FICANADACHRISTIAN}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FICANADACHRISTIAN_METADATA}
    />
    <Composition
      id="FICHINAAMERICAVISIT"
      component={FICHINAAMERICAVISIT}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FICHINAAMERICAVISIT_METADATA}
    />
    <Composition
      id="FICHRISTIANRESTAURANT"
      component={FICHRISTIANRESTAURANT}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FICHRISTIANRESTAURANT_METADATA}
    />
    <Composition
      id="FICROSSCHRISTIAN"
      component={FICROSSCHRISTIAN}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FICROSSCHRISTIAN_METADATA}
    />
    <Composition
      id="FICROSSSAFEGAY"
      component={FICROSSSAFEGAY}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FICROSSSAFEGAY_METADATA}
    />
    <Composition
      id="FIFLOWERCRYING"
      component={FIFLOWERCRYING}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIFLOWERCRYING_METADATA}
    />
    <Composition
      id="FIFLOWERLANDED"
      component={FIFLOWERLANDED}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIFLOWERLANDED_METADATA}
    />
    <Composition
      id="FIFLOWERMUSLIM"
      component={FIFLOWERMUSLIM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIFLOWERMUSLIM_METADATA}
    />
    <Composition
      id="FIFLOWERSISTERS"
      component={FIFLOWERSISTERS}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIFLOWERSISTERS_METADATA}
    />
    <Composition
      id="FIFLOWERUGANDA"
      component={FIFLOWERUGANDA}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIFLOWERUGANDA_METADATA}
    />
    <Composition
      id="FIHUMUSRESPECT"
      component={FIHUMUSRESPECT}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIHUMUSRESPECT_METADATA}
    />
    <Composition
      id="FIINDONESIACHRISTIANSAFE"
      component={FIINDONESIACHRISTIANSAFE}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIINDONESIACHRISTIANSAFE_METADATA}
    />
    <Composition
      id="FIINDONESIAHOME"
      component={FIINDONESIAHOME}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIINDONESIAHOME_METADATA}
    />
    <Composition
      id="FIINDONESIANINSTAGRAM"
      component={FIINDONESIANINSTAGRAM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIINDONESIANINSTAGRAM_METADATA}
    />
    <Composition
      id="FIINDONESIAZIONIST"
      component={FIINDONESIAZIONIST}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIINDONESIAZIONIST_METADATA}
    />
    <Composition
      id="FIIQAMPEACE"
      component={FIIQAMPEACE}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIIQAMPEACE_METADATA}
    />
    <Composition
      id="FIIRAQJEWSPERSECUTED"
      component={FIIRAQJEWSPERSECUTED}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIIRAQJEWSPERSECUTED_METADATA}
    />
    <Composition
      id="FIIRELANDSURPRISED"
      component={FIIRELANDSURPRISED}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIIRELANDSURPRISED_METADATA}
    />
    <Composition
      id="FIJAFFAMUSLIM"
      component={FIJAFFAMUSLIM}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIJAFFAMUSLIM_METADATA}
    />
    <Composition
      id="FIJEWHATEEUROPE"
      component={FIJEWHATEEUROPE}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIJEWHATEEUROPE_METADATA}
    />
    <Composition
      id="FIMEETBADIK"
      component={FIMEETBADIK}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIMEETBADIK_METADATA}
    />
    <Composition
      id="FIMOROCCOCOUPLE"
      component={FIMOROCCOCOUPLE}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIMOROCCOCOUPLE_METADATA}
    />
    <Composition
      id="FINIGERIAWORK"
      component={FINIGERIAWORK}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FINIGERIAWORK_METADATA}
    />
    <Composition
      id="FIONEWAYTICKET"
      component={FIONEWAYTICKET}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIONEWAYTICKET_METADATA}
    />
    <Composition
      id="FIPOLISHPRIEST"
      component={FIPOLISHPRIEST}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIPOLISHPRIEST_METADATA}
    />
    <Composition
      id="FIRELIGIOUSJEWEXPLAIN"
      component={FIRELIGIOUSJEWEXPLAIN}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIRELIGIOUSJEWEXPLAIN_METADATA}
    />
    <Composition
      id="FIRELIGIOUSJEWGARMENT"
      component={FIRELIGIOUSJEWGARMENT}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FIRELIGIOUSJEWGARMENT_METADATA}
    />
    <Composition
      id="FISRILANKANWORKER"
      component={FISRILANKANWORKER}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={1}
      calculateMetadata={FISRILANKANWORKER_METADATA}
    />
  </Folder>
);
